### ISSUE TITLE
versioning

### ISSUE THREAD

**Issue by Nivekiba** [ceph/cephadm-ansible#219]
Is there a way to force a specific version of ceph to be installed ?

**Comment by pcuzner** [comment]
@Nivekiba since cephadm-ansible isn't deploying ceph itself, you can use cephadm to deploy a specific version. The preflight playbook makes sure the repos are set up and installs the latest version of cephadm and ceph-common on each node.

This means that you'll get the default ceph image associated with the version of cephadm that has been installed. However, you can supply a --image on the boostrap to pick a specific version too. For example when the preflight runs with quincy, the default image cephadm will use is quay.io/ceph/ceph:v17 but you can override that with 

```cephadm --image=quay.io/ceph/ceph:v17.2.5 bootstrap <options>```

**Comment by Nivekiba** [comment]
Hi @pcuzner 
I will try it, thank you.

**Comment by Nivekiba** [comment]
Hello, 
I reopen this because i have another question which is a variation of the original one.

Is there a way to specify a ceph locally built version ? ( that I compiled myself)
In such a way that instead of fetching ceph-common package like cephadm-preflight playbook does, we fetch the locally installed one.

**Comment by mstinsky** [comment]
@Nivekiba Not sure if you are mixing up a couple of things here.
The preflight "only" sets up cephadm, docker and things that are required for cephadm to run.
Ceph itself is deployed via cephadm and not from cephadm-ansible.

If you want to change the source code of the running ceph installation you need to build containers for your compiled code. cephadm by default uses container build from this repo https://github.com/ceph/ceph-container
After that you can tell cephadm to deploy your self build containers as @pcuzner mentioned.

**Comment by Nivekiba** [comment]
Ok, thank you
I thought Cephadm was building the containers itself using  URLs given for a custom repo
