### ISSUE TITLE
Preflight fails with "nothing provides libthrift-0.15.0.so()(64bit) needed by ceph-common-2:17.2.7-0.el9.x86_64"

### ISSUE THREAD

**Issue by tomkivlin** [ceph/cephadm-ansible#287]
Running cephadm-preflight.yml against RHEL9.2 in preparation for Ceph 6 fails with:

```bash
fatal: [ceph1]: FAILED! => changed=false 
  attempts: 3
  failures: []
  msg: |-
    Depsolve Error occurred:
     Problem: cannot install the best candidate for the job
      - nothing provides libthrift-0.15.0.so()(64bit) needed by ceph-common-2:17.2.7-0.el9.x86_64
  rc: 1
  results: []
```

Enabling the EPEL repository (e.g. using the [geerlingguy.repo-epel](https://github.com/geerlingguy/ansible-role-repo-epel) role) as a "pre-preflight" step means the preflight playbook works but given the preflight playbook is about preparing the hosts and installing prerequisites it feels that this should be part of that.

**Comment by asm0deuz** [comment]
@tomkivlin We do not enable EPEL on RHEL systems as RH does only support packages they provide. libthrift-0.15.0.so should be available from one of their repositories (probably in rhceph-6-tools-for-rhel-9).

I will reproduce the issue and check with RH

**Comment by asm0deuz** [comment]
@tomkivlin
I reproduced your issue, this is due to a misconfiguration. When installing Ceph on a RHEL setup you have to set the variable ceph_origin to "rhcs". By default that variable is set to "community", therefore it will enable ceph stable repository which is not supported by RH and indeed then EPEL is required.
By setting "rhcs", the RH repositories are configured and that dependency issue does not happen.

Hope this helps
